spring:
  datasource:
    url: jdbc:mysql://sql12.freesqldatabase.com/sql12549717
    username: sql12549717
    password: 3sTapdKCUJ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    root: info
  file:
    path: /
    name: log.txt

admin:
  username: shreyas
  password: shreyas123
  email: shreyas@gmail.com